# Don't print a new line at the start of the prompt
# add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
# [character]      # The name of the module we are confguring is "character"
# symbol = "âœ"     # The "symbol" segment is being set to "âœ"

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

# Overwrite a default_prompt_order and  use custom prompt_order
# prompt_order=["rust","line_break","package","line_break","character"]

# [battery]
# full_symbol = "ğŸ”‹"
# charging_symbol = "âš¡ï¸"
# discharging_symbol = "ğŸ’€"

# [character]
# symbol = "âœ"
# error_symbol = "âœ—"
# use_symbol_for_status = true

# [cmd_duration]
# min_time = 4


# [directory]
# truncation_length = 8

# [git_branch]
# symbol = "ğŸŒ± "
# truncation_length = "4"
# truncation_symbol = ""

# [git_state]
# progress_divider = " of "
# cherry_pick = "ğŸ’ PICKING"

# [git_status]
# conflicted = "ğŸ³"
# ahead = "ğŸğŸ’¨"
# behind = "ğŸ˜°"
# diverged = "ğŸ˜µ"
# untracked = "ğŸ¤·â€"
# stashed = "ğŸ“¦"
# modified = "ğŸ“"
# staged = "â•"
# renamed = "ğŸ‘…"
# deleted = "ğŸ—‘"

# [golang]
# symbol = "ğŸğŸ’¨ "

# [hostname]
# ssh_only = false
# prefix = "âŸª"
# suffix = "âŸ«"
# disabled = false

# [jobs]
# symbol = "+ "
# threshold = 4

# [line_break]
# disabled = true

# [nix_shell]
# disabled = true
# use_name = true
# impure_msg = "impure shell"
# pure_msg = "pure shell"


# [nodejs]
# symbol = "ğŸ¤– "

# [package]
# symbol = "ğŸ "

# [python]
# symbol = "ğŸ‘¾ "
# pyenv_version_name = true
# pyenv_prefix = "foo "

# [ruby]
# symbol = "ğŸ”º "

[rust]
symbol = "âš™ï¸ "

# [username]
# disabled = true
